// <auto-generated />
using System;
using HotelListing.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210226224103_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6069422e-0248-44fd-b969-9626b14df3c2"),
                            Name = "Egypt",
                            ShortName = "Egy"
                        },
                        new
                        {
                            Id = new Guid("d05aaafb-1ac1-4c94-8582-b97dbbe2836b"),
                            Name = "Sudan",
                            ShortName = "Sn"
                        },
                        new
                        {
                            Id = new Guid("b9923232-d27e-4af4-8768-6c58ad665d45"),
                            Name = "Libya",
                            ShortName = "Li"
                        },
                        new
                        {
                            Id = new Guid("71cad3bd-df3c-47d0-b621-3de868fcaa69"),
                            Name = "Jamaica",
                            ShortName = "Jm"
                        });
                });

            modelBuilder.Entity("HotelListing.Models.Hostel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hostels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("458a2291-e139-428b-bc96-f26e9d176cd5"),
                            Address = "Cairo",
                            CountryId = new Guid("6069422e-0248-44fd-b969-9626b14df3c2"),
                            Name = "Hostel 1 Resort and Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("25981683-c283-465c-81f5-5243f156f788"),
                            Address = "Cairo",
                            CountryId = new Guid("d05aaafb-1ac1-4c94-8582-b97dbbe2836b"),
                            Name = "Hostel 2 Resort and Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("0b76fe3d-486d-4508-95d9-73ce5840bd5b"),
                            Address = "Cairo",
                            CountryId = new Guid("b9923232-d27e-4af4-8768-6c58ad665d45"),
                            Name = "Hostel 3 Resort and Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("723a9bfd-bfe9-4b44-bae3-340d5441aabe"),
                            Address = "Cairo",
                            CountryId = new Guid("71cad3bd-df3c-47d0-b621-3de868fcaa69"),
                            Name = "Hostel 4 Resort and Spa",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("HotelListing.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4353d1b0-4661-4217-a31b-fc4296896caa"),
                            Address = "Cairo",
                            CountryId = new Guid("6069422e-0248-44fd-b969-9626b14df3c2"),
                            Name = "Sandals Resort and Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("e42ab626-1e82-4c23-98e5-d39f078fadf9"),
                            Address = "Cairo",
                            CountryId = new Guid("d05aaafb-1ac1-4c94-8582-b97dbbe2836b"),
                            Name = "Sta Resort and Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("68daa73b-7914-4742-92b3-a79873da4ecc"),
                            Address = "Cairo",
                            CountryId = new Guid("b9923232-d27e-4af4-8768-6c58ad665d45"),
                            Name = "Mgme Resort and Spa",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = new Guid("b57b14e7-0622-41b3-8c91-80bd943736db"),
                            Address = "Cairo",
                            CountryId = new Guid("71cad3bd-df3c-47d0-b621-3de868fcaa69"),
                            Name = "New Rose Resort and Spa",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("HotelListing.Models.Hostel", b =>
                {
                    b.HasOne("HotelListing.Models.Country", "Country")
                        .WithMany("Hostels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.Models.Hotel", b =>
                {
                    b.HasOne("HotelListing.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.Models.Country", b =>
                {
                    b.Navigation("Hostels");

                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
